name: myfirstaction
on: push
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: disply
        run: echo "${{ toJSON(github) }}"